### ISSUE TITLE
requirement 中的 random 似乎没有这个包

### ISSUE THREAD

**Issue by wangxinsheng0102** [Ascotbe/Medusa#1]
1 bs4
  2 fake-useragent
  3 requests
  4 urllib3
  5 python-nmap
  6 PyMySQL
  7 IPy
  8 scrapy
  9 tqdm
 10 dnspython
 11 tldextract
 12 random <-------------

**Comment by Ascotbe** [comment]
> 1 bs4
> 2 fake-useragent
> 3 requests
> 4 urllib3
> 5 python-nmap
> 6 PyMySQL
> 7 IPy
> 8 scrapy
> 9 tqdm
> 10 dnspython
> 11 tldextract
> 12 random <-------------

这个包是python自带的不需要安装，已更新，多谢反馈
