### ISSUE TITLE
Windows下运行乱码

### ISSUE THREAD

**Issue by yizhicaiji123** [Ascotbe/Medusa#18]
环境：python3.7+win10
![image](https://user-images.githubusercontent.com/51145610/86330388-320d8400-bc7a-11ea-8ff3-98a4cf979833.png)
![image](https://user-images.githubusercontent.com/51145610/86330442-45205400-bc7a-11ea-91b9-37aca3aa3322.png)
![image](https://user-images.githubusercontent.com/51145610/86330280-08ecf380-bc7a-11ea-948c-615c14bf6da7.png)

**Comment by Ascotbe** [comment]
推荐使用Windows Terminal  用这个命令行，windows原生的交互对于一些编码无法解析
