### ISSUE TITLE
[help] 扫描结果保存在哪，为什么我看到是空的

### ISSUE THREAD

**Issue by bigbeef** [Ascotbe/Medusa#21]
[ + ] Scanning across modules: AllMod             
[ + ] Medusa scan progress bar: 100%|####################################################################################################################################################################| 241/241 [00:09<00:00, 24.99it/s]
[ + ] Medusa cleanup thread progress: 100%|##############################################################################################################################################################| 241/241 [02:04<00:00,  1.93it/s]
[ ! ] Scan is complete, please see the ScanResult file

**Comment by Ascotbe** [comment]
空的就是没有，具体可以看文档有路径
