### ISSUE TITLE
how fix this

### ISSUE THREAD

**Issue by Kalimon12** [Ascotbe/Medusa#30]
root@kali:~/Desktop/Medusa-master# python3 MedusaScan.py -f sub.txt

                                            
  __  __ ______  ____ ___ _______ _   _   _ 
 |  \/  |____  ||__  |_  |____   | | | | | |
 | |\/| | _  | |   | | | |    | || | | | | |
 | |  | || | |_____| | | |    | || |/ /_/ / 
 |_|  |_|| |  /____/\_\|_|    |_||_______/  
         |_|                                

 
                                                                                   
      Blog  https://www.ascotbe.com  |  v0.92    

Traceback (most recent call last):
  File "MedusaScan.py", line 158, in <module>
    Subdomain=args.Subdomain#开启子域名枚举
AttributeError: 'Namespace' object has no attribute 'Subdomain'

**Comment by Ascotbe** [comment]
https://github.com/Ascotbe/Medusa/releases/tag/v0.92
