### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by coolksj** [Ascotbe/Medusa#31]
**Describe the bug**||**描述错误**
冲着有中文提示的 DEMO 来的， 英文早都看腻了。

**To Reproduce**||**重现**

两个错误， 
一个是安装时
pip3 install -r Medusa.txt
ERROR: Cannot install -r Medusa.txt (line 25) and cryptography==3.1.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested cryptography==3.1.1
    mitmproxy 4.0.4 depends on cryptography<2.4 and >=2.1.4

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

----------------------------------------
一个是运行时
python3 MedusaScan.py -u www.xxxxxxx.com or python3 MedusaScan.py -u https://www.xxxxxxx.com

都会提示 unsupported operand type(s) for +: 'NoneType' and 'str' 

Process Process-116:
Traceback (most recent call last):
  File "/usr/Medusa/Modules/Cms/EasyTalk/EasyTalkSQLInjectionVulnerability10.py", line 28, in medusa
    payload_url = url + payload
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/Medusa/Modules/Cms/EasyTalk/EasyTalkSQLInjectionVulnerability10.py", line 41, in medusa
    _l = ErrorLog().Write("Plugin Name:"+_+" || Target Url:"+url,e)#调用写入类
TypeError: can only concatenate str (not "NoneType") to str
[ + ] Medusa scan progress bar:  79%|################################################################################################################################7                                   | 190/242 [00:01<00:00, 97.58it/s]Process Process-199:
Traceback (most recent call last):
  File "/usr/Medusa/Modules/OA/Seeyou/SeeyouMultipleSQLInjectionVulnerabilities.py", line 34, in medusa
    payload_url = url+payload
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/Medusa/Modules/OA/Seeyou/SeeyouMultipleSQLInjectionVulnerabilities.py", line 47, in medusa
    _l = ClassCongregation.ErrorLog().Write("Plugin Name:"+_+" || Target Url:"+url,e)#调用写入类
TypeError: can only concatenate str (not "NoneType") to str
[ + ] Medusa scan progress bar:  88%|#################################################################################################################################################                   | 214/242 [00:02<00:00, 96.96it/s]Process Process-214:
Traceback (most recent call last):
  File "/usr/Medusa/Modules/OA/Weaver/WeaverDatabaseConfigurationLeakVulnerability.py", line 29, in medusa
    payload_url = url+payload
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/Medusa/Modules/OA/Weaver/WeaverDatabaseConfigurationLeakVulnerability.py", line 41, in medusa
    _l = ClassCongregation.ErrorLog().Write("Plugin Name:"+_+" || Target Url:"+url,e)#调用写入类
TypeError: can only concatenate str (not "NoneType") to str
[ + ] Medusa scan progress bar: 100%|####################################################################################################################################################################| 242/242 [00:04<00:00, 58.69it/s]
[ + ] Medusa cleanup thread progress:   0%|                                                                                                                                                                        | 0/242 [00:00<?, ?it/s]Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by ysoserial.payloads.CommonsCollections5 (file:/usr/Medusa/Tool/ysoserial.jar) to field javax.management.BadAttributeValueExpException.val
WARNING: Please consider reporting this to the maintainers of ysoserial.payloads.CommonsCollections5
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
WARNING:root:got EOF error, stop recv loop!
[ ! ] Unable to get dnslog, please replace ceye! 
[ ! ] Unable to get dnslog, please replace ceye! 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
WARNING:root:
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true

**Related system description:**||**相关系统说明:**

Kali Lunix

**Additional context**||**其他内容**

**Comment by Ascotbe** [comment]
![image](https://user-images.githubusercontent.com/33721903/102430738-dc713c00-404d-11eb-89b9-822ee90ffd68.png)
看这里
安装问题的话mitmproxy 可以忽略不计，因为这个包目前用不到
