### ISSUE TITLE
JAVA Bug

### ISSUE THREAD

**Issue by zygds** [Ascotbe/Medusa#34]
**Describe the bug**
**截图**
![image](https://user-images.githubusercontent.com/73819467/103738301-c3492300-502e-11eb-86e6-dcc315ecd617.png)

**相关系统说明:**
- mac os 11.1 bigsur
- python3.9
- rostta2
```
java --version
openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment Zulu15.28+1013-CA (build 15.0.1+9)
OpenJDK 64-Bit Server VM Zulu15.28+1013-CA (build 15.0.1+9, mixed mode)
```

**Comment by Ascotbe** [comment]
Java环境装了吗？版本是否是1.8的jdk?

**Comment by Ascotbe** [comment]
还有你打码的域名泄露了:hushed:

**Comment by zygds** [comment]
openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment Zulu15.28+1013-CA (build 15.0.1+9)
OpenJDK 64-Bit Server VM Zulu15.28+1013-CA (build 15.0.1+9, mixed mode)

**Comment by Ascotbe** [comment]
推荐是使用java官方的jdk，最好不要用openjdk,并且是1.8版本的

**Comment by zygds** [comment]
好吧，可能是jdk版本的问题😂

**Comment by Ascotbe** [comment]
你用的是15的jdk,太新了

**Comment by zygds** [comment]
只支持zulu😅，也许我可以换一个版本看看，但是bug也更多😅

**Comment by Ascotbe** [comment]
mac 可以直接装官方的jdk

```
 ascotbe@orange  ~/code/Medusa   master  java  -version
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
 ascotbe@orange  ~/code/Medusa   master  jdk11         
 ascotbe@orange  ~/code/Medusa   master  java  -version
java version "11.0.9" 2020-10-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.9+7-LTS, mixed mode)
```

**Comment by zygds** [comment]
我的是m1，尴尬😅

**Comment by Ascotbe** [comment]
那你找下openjdk 1.8的那个版本吧，m1的无解

**Comment by zygds** [comment]
![image](https://user-images.githubusercontent.com/73819467/103740208-d01b4600-5031-11eb-98fd-bd50df95f01f.png)
tai n太难受了，这么好的工具我却无法享受，难受

**Comment by zygds** [comment]
加油⛽️

**Comment by Ascotbe** [comment]
等后面用docker吧，直接附带web的那种

**Comment by zygds** [comment]
大佬加个微信如何😂，你微信多少呀

**Comment by Ascotbe** [comment]
你可以加群，项目有群号

**Comment by zygds** [comment]
表哥答案是啥，来个[友联 吧](https://blog.zygd.site)
