### ISSUE TITLE
遇到两个问题

### ISSUE THREAD

**Issue by uuuuuuzeus** [Ascotbe/Medusa#38]
第一个：qq群密码是什么啊？我试过了
https://github.com/Ascotbe/Medusa.git
http://medusa.ascotbe.com/Documentation/#/
https://www.ascotbe.com/Loophole
全部不对。。。。。。

第二个问题：
我部署的是docker环境，已经部署好了，但是打开之后验证码显示不出来，提示网络错误。这种情况应该怎么解决？
按理说docker环境应该是开箱即用啊，不存在需要进去再调整前后端对接。
而且我用docker exec id号进去想执行命令，发现docker自动死掉了。

**Comment by Ascotbe** [comment]
1.http://medusa.ascotbe.com
2.docker环境是正常的，如果是服务器请使用手动部署，docker环境源请使用官方源，还有网络错误是前后端的地址问题，只有服务器部署会这样，需要手动改IP
