### ISSUE TITLE
[help] redis配置的问题

### ISSUE THREAD

**Issue by xiaoqi7654321** [Ascotbe/Medusa#39]
**redis访问默认localhost:6379如何修改呢 我尝试在本机安装了一个redis 端口密码等都是默认的 还是无法连接到 请问该如何配置 config.py文件已经设置但没生效**

**Screenshots**||**截图**
![image](https://user-images.githubusercontent.com/59239845/109745966-991b7800-7c0f-11eb-8ee4-d117f9bc1e77.png)

 - Detailed system version, kernel and other information||详细的系统版本，内核等信息
 - Python related version number||Python相关的版本号
 - Project version number||项目版本号

**Comment by xiaoqi7654321** [comment]
小白一枚 求大佬解惑

**Comment by xiaoqi7654321** [comment]
版本为 Lunix

**Comment by xiaoqi7654321** [comment]
版本为 WEB 版本 linux安装

**Comment by staySober** [comment]
你是怎么解决的，我也遇到了这个问题， 是不是配置有问题
