### ISSUE TITLE
[help] 启动web后验证码出不来 XMLHttpRequest报错

### ISSUE THREAD

**Issue by xiaoqi7654321** [Ascotbe/Medusa#40]
**Describe the bug**||**描述错误**

前端界面出来了 但是加载不到验证码 我试了用postman请求9999端口的验证码接口是通的 请大佬帮忙看下我的错误

**Screenshots**||**截图**
F12报错截图
![image](https://user-images.githubusercontent.com/59239845/109780805-4f985080-7c42-11eb-8dac-954d357fbcc4.png)

登录界面
![image](https://user-images.githubusercontent.com/59239845/109780908-65a61100-7c42-11eb-87cf-7cd64692e702.png)

/Medusa/Vue/faceConfig.js配置截图
![image](https://user-images.githubusercontent.com/59239845/109781145-9ede8100-7c42-11eb-939c-bcf738e9d79b.png)

**Related system description:**||**相关系统说明:**

 centos7 WEB部署的

**Comment by Ascotbe** [comment]
@dieLion 你看看

**Comment by Ascotbe** [comment]
链接地址是http://192.168.182.247:9999/api/
而不是http://:192.168.182.247:9999/api/
你多了个“:”号

**Comment by xiaoqi7654321** [comment]
感谢感谢 疏忽了

**Comment by xiaoqi7654321** [comment]
请问web版本的 在界面上下发扫描任务 扫描不出来任何东西 使用shell命令去扫描就有 我应该去哪里找问题呢 

web 截图
![image](https://user-images.githubusercontent.com/59239845/109923990-92b5fa80-7cfa-11eb-8bf3-ad61f6a303ef.png)

shell截图
![image](https://user-images.githubusercontent.com/59239845/109924028-a3667080-7cfa-11eb-9f54-f4a0e8aa4b18.png)
