### ISSUE TITLE
[Bug]Web版本使用docker搭建后访问提示“Network Error”

### ISSUE THREAD

**Issue by si1entgr0** [Ascotbe/Medusa#41]
**Describe the bug**||**描述错误**
A clear and concise description of what the bug is.||清楚简洁地说明错误是什么。

web版本按照docker安装的步骤进行，搭建完成中间没有报错，但登录时提示“Network Error”

**To Reproduce**||**重现**
Steps to reproduce the behavior and paste the relevant data package:||重现行为的步骤，并贴上相关的数据包：

**Screenshots**||**截图**
If applicable, add screenshots to help explain your problem.||如果适用，请添加屏幕截图以帮助解释您的问题。
报错截图如下：https://raw.githubusercontent.com/si1entgr0/si1egimg/master/20210310145117.png

**Related system description:**||**相关系统说明:**

 - Detailed system version, kernel and other information||详细的系统版本，内核等信息
 - Python related version number||Python相关的版本号
 - Project version number||项目版本号
 
Linux localhost.localdomain 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Docker version 20.10.2, build 2291f61

**Log content**||**日志内容**
Please post the log content of the error time period||请贴上报错时间段的日志内容关内容

**Additional context**||**其他内容**
Write relevant content that needs to be added here.||这边写上需要补充的相关内容

**Comment by Ascotbe** [comment]
换手动安装
