### ISSUE TITLE
redis配置如果使用带特殊符号的密码 提示 密码无效

### ISSUE THREAD

**Issue by staySober** [Ascotbe/Medusa#47]
**Describe the bug**||**描述错误**
当redis的密码包含 !@# 等特殊符号,时 redis连接不上

**To Reproduce**||**重现**
Steps to reproduce the behavior and paste the relevant data package:||重现行为的步骤，并贴上相关的数据包：
1. redis使用带 !@# 等符号的密码
![image](https://user-images.githubusercontent.com/20500978/118777272-7702cf00-b8bb-11eb-945a-3a9fb1d57b6f.png)
2.Medusa config配置文件配置相同的密码
![image](https://user-images.githubusercontent.com/20500978/118777415-9c8fd880-b8bb-11eb-84b0-f12062f3feac.png)
3. Medusa 提示密码无效
![image](https://user-images.githubusercontent.com/20500978/118777552-c47f3c00-b8bb-11eb-9df5-6c1b57c5e919.png)

**Related system description:**||**相关系统说明:**

Linux Centos7
python 3.7
java 8
Medusa Web master分支代码

猜测:  配置文件里的密码可能需要转义
如果密码不用单引号 和 双引号 包围, 并用“\” 转译字符  实际测试无效

**Comment by chenjiewei123** [comment]
注册的时候提示服务器是什么原因
![image](https://user-images.githubusercontent.com/39107839/124323476-f7ec0080-dbb3-11eb-8e3a-f2180a87fdc9.png)

**Comment by chAamirKhan** [comment]
> 注册的时候提示服务器是什么原因
> ![image](https://user-images.githubusercontent.com/39107839/124323476-f7ec0080-dbb3-11eb-8e3a-f2180a87fdc9.png)
我也是

**Comment by Ascotbe** [comment]
> > 注册的时候提示服务是什么原因
> > 我也是
> > ![图片](https://user-images.githubusercontent.com/39107839/124323476-f7ec0080-dbb3-11eb-8e3a-f2180a87fdc9.png)

要么是验证码问题，要么是key不对，可以产考文档是不是配置错误了

**Comment by isaac1216** [comment]
> > > 注册的时候提示服务是什么原因
> > > 我也是
> > > ![图片](https://user-images.githubusercontent.com/39107839/124323476-f7ec0080-dbb3-11eb-8e3a-f2180a87fdc9.png)
> 
> 要么是验证码问题，要么是key不对，可以产考文档是不是配置错误了

我是按着说明在虚拟机上搭的，请问验证码加载不出来是怎么回事，提示network error，是我少了什么配置吗

**Comment by Ascotbe** [comment]
> > > > 注册的时候提示服务是什么原因
> > > > 我也是
> > > > ![图片](https://user-images.githubusercontent.com/39107839/124323476-f7ec0080-dbb3-11eb-8e3a-f2180a87fdc9.png)
> > 
> > 
> > 要么是验证码问题，要么是key不对，可以产考文档是不是配置错误了
> 
> 我是按着说明在虚拟机上搭的，请问验证码加载不出来是怎么回事，提示network error，是我少了什么配置吗？用的firefox浏览器，运行python3的窗口会报错
> [18/Sep/2021 19:39:11] code 400, message Bad request version ('\x8f\x80Ô\x8a±xÓ¤=ÔïôØ\x8d4AÖDS"¦gë\x00$\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
> [18/Sep/2021 19:39:11] You're accessing the development server over HTTPS, but it only supports HTTP.

你这是后端开了http，前端却用HTTPS访问，你看下前后端配置是否都是http

**Comment by Zup1993** [comment]
请问如何关闭验证码，你这个搞了半天只能本地，外部请求的话，验证码地址127.0.0.1:9999，这个看vue.config.js改了也不是。
![image](https://user-images.githubusercontent.com/39846114/145545270-10900c24-7c04-4031-878a-b768cfb52177.png)
心态崩了啊！

**Comment by nanshihui** [comment]
已经收到哦，我会尽快回复你。I have received your email and will reply to you ASAP. Thanks

**Comment by Luolanjiao** [comment]
请问解决了吗
