### ISSUE TITLE
什么都扫不出来是什么鬼

### ISSUE THREAD

**Issue by handbye** [Ascotbe/Medusa#5]
比如，我自建的一个靶场是存在struts2漏洞的，用正常的扫描器扫描是可以扫出来的：
![image](https://user-images.githubusercontent.com/26617058/78685122-e5890580-7923-11ea-9087-670ebeb873aa.png)
而用美杜莎什么都扫不来，扫了好几遍都扫不来。
![image](https://user-images.githubusercontent.com/26617058/78685226-081b1e80-7924-11ea-97cd-bfe9f3fc38d7.png)

**Comment by Ascotbe** [comment]
> 例如，我自建的一个靶场是存在struts2断裂的，用正常的扫描器扫描是可以扫出来的： 而用美杜莎什么都扫不来，扫了好几遍都扫不来。
> ![图片](https://user-images.githubusercontent.com/26617058/78685122-e5890580-7923-11ea-9087-670ebeb873aa.png)
> 
> ![图片](https://user-images.githubusercontent.com/26617058/78685226-081b1e80-7924-11ea-97cd-bfe9f3fc38d7.png)

你搭建的靶场连接给我看看

**Comment by handbye** [comment]
> > 例如，我自建的一个靶场是存在struts2断裂的，用正常的扫描器扫描是可以扫出来的： 而用美杜莎什么都扫不来，扫了好几遍都扫不来。
> > ![图片](https://user-images.githubusercontent.com/26617058/78685122-e5890580-7923-11ea-9087-670ebeb873aa.png)
> > ![图片](https://user-images.githubusercontent.com/26617058/78685226-081b1e80-7924-11ea-97cd-bfe9f3fc38d7.png)
> 
> 你把靶场连接给我看看，我搭个试试，struts2这个模块我没写，上次应急的时候抄的别人工具

https://github.com/vulhub/vulhub/tree/master/struts2   docker一键搭建

**Comment by Ascotbe** [comment]
![image](https://user-images.githubusercontent.com/33721903/78738542-b191fc80-7984-11ea-82a4-142bdb12ad4f.png)
我测试了搭建的是005的但是扫描出其他的漏洞，请已Lucifer1993大佬的struts2scan为准，vulhub搭建的漏洞有些和实战不符，具体请以实际操作为主

**Comment by Ascotbe** [comment]
后续实战如果遇到再更改吧，目前还是用别人的项目代码

**Comment by handbye** [comment]
> 后续实战如果遇到再更改吧，目前还是用别人的项目代码

ok吧，遇到实际情况再试试

**Comment by Ascotbe** [comment]
> > 后续实战如果遇到再更改吧，目前还是用别人的项目代码
> 
> ok吧，遇到实际情况再试试

已重构删除多余脚本，剩下通用性struts2漏洞，使用方法比如http://127.0.0.1:8080/example/HelloWorld.action，需要跟上完整的路径

**Comment by handbye** [comment]
> > > 后续实战如果遇到再更改吧，目前还是用别人的项目代码
> > 
> > 
> > ok吧，遇到实际情况再试试
> 
> 已重构删除多余脚本，剩下通用性struts2漏洞，使用方法比如[http://127.0.0.1:8080/example/HelloWorld.action，需要跟上完整的路径](http://127.0.0.1:8080/example/HelloWorld.action%EF%BC%8C%E9%9C%80%E8%A6%81%E8%B7%9F%E4%B8%8A%E5%AE%8C%E6%95%B4%E7%9A%84%E8%B7%AF%E5%BE%84)

good!
