### ISSUE TITLE
安装爆错

### ISSUE THREAD

**Issue by sp4rkw** [Ascotbe/Medusa#59]
### 当前使用的操作系统

- [ ] macOS
- [ ] Windows
- [X] Linux

### 描述错误

系统环境ubuntu18.04

### 重现步骤

```bash
1、使用docker安装，按照文档来，提示Unable to find image 'medusa_web:latest' locally
去dockerhub找了下，没有这个镜像，该如何解决
2、直接http安装，安装步骤来，run.sh执行中爆错，提示80端口已经被占用（服务器新建的服务器，不存在其他任何服务干扰）
```

### 接口位置

无

### 相关环境说明

无

### 日志内容

无

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/ascotbe/Medusa/issues)，以确保该错误尚未被报告。

**Comment by Ascotbe** [comment]
我前两天刚用docker装的不存在你说的问题，用的是最新版本？

**Comment by Ascotbe** [comment]
如果您还有什么问题可以重新打开该issue，我先关闭了

**Comment by sp4rkw** [comment]
这个问题解决了，原因是我直接拖的github源码，所以一直失败

**Comment by Qclover** [comment]
> 这个问题解决了，原因是我直接拖的github源码，所以一直失败

我也遇到这个问题了，后来你是怎么解决的
