### ISSUE TITLE
test

### ISSUE THREAD

**Issue by supascotbe** [Ascotbe/Medusa#66]
### 这是一个什么样的功能？

test

### 这个功能可以解决什么问题？

test

### 额外描述

test

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/ascotbe/Medusa/issues)，以确保这项功能尚未被请求。

**Comment by Ascotbe** [comment]
To support our project, please file the issue after you starred the repo. Thanks! :)
