### ISSUE TITLE
你好，git监控能不能按照项目创建时间排序

### ISSUE THREAD

**Issue by SherLocZ** [Ascotbe/Medusa#68]
### 这是一个什么样的功能？

是这个样子的，你按照项目更新时间来排序，有些很久的项目更新了就置顶了，GIThub监控是想看最新有什么漏洞出现

所以你能不能【按照项目创建时间】来排序
![image](https://user-images.githubusercontent.com/28530859/147642697-753e1f00-a533-4936-87ad-e2dde15bb4b1.png)

谢谢

### 这个功能可以解决什么问题？

是这个样子的，你按照项目更新时间来排序，有些很久的项目更新了就制定了，GIThub监控是想看最新有什么漏洞出现

所以你能不能【按照项目创建时间】来排序

![image](https://user-images.githubusercontent.com/28530859/147642691-7577095e-6103-44b4-8a24-e4a2cf4913be.png)

谢谢

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/ascotbe/Medusa/issues)，以确保这项功能尚未被请求。

**Comment by SherLocZ** [comment]
123123

**Comment by Ascotbe** [comment]
v1.0.111🌴 版本中已修复该问题，感谢您的意见，祝您生活愉快 :)
