### ISSUE TITLE
Docker构建和运行出现bug,无法正常运行，多次排查bug仍无法解决&&服务器上运行后崩溃&&登录图片验证码刷新不出来

### ISSUE THREAD

**Issue by Qclover** [Ascotbe/Medusa#70]
### 当前使用的操作系统

- [X] macOS
- [ ] Windows
- [X] Linux

### 描述错误

docker 运行出错，无法成功构建，按照bug排查，尝试了多种可能问题，一天了任无法解决。

### 重现步骤

```bash
1.ascotbe/medusa:latest镜像打包成Medusa.tat.gz放入本地Medusa目录

2.腾讯云服务器和MACOS 上运行docker build -t medusa_web .均报错，无法成功构建
bug1:
#36 3.187 npm ERR! code ENOENT
#36 3.190 npm ERR! syscall open
#36 3.190 npm ERR! path /Medusa/Vue/package.json
#36 3.195 npm ERR! enoent ENOENT: no such file or directory, open '/Medusa/Vue/package.json'
bug2:
Fail at the Medusa@0.1.0 serve script
3.本地服务器搭建后首次运行登录图片验证码无法刷新。重启重新再运行无法跑成功。Vue 目录下运行npm run serve 先是崩溃，后直接报错

问题排查了一天，无法解决。希望能获取帮助。帮忙解决问题
```

### 接口位置

null

### 相关环境说明

腾讯云服务器
Linux VM-4-13-ubuntu 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
python3.8
MACOS M1 arm内核 

### 日志内容

1.docker
 => ERROR [32/41] RUN npm run serve                                                                            3.2s
------
 > [32/41] RUN npm run serve:
#36 3.187 npm ERR! code ENOENT
#36 3.190 npm ERR! syscall open
#36 3.190 npm ERR! path /Medusa/Vue/package.json
#36 3.191 npm ERR! errno -2
#36 3.195 npm ERR! enoent ENOENT: no such file or directory, open '/Medusa/Vue/package.json'
#36 3.196 npm ERR! enoent This is related to npm not being able to find a file.
#36 3.196 npm ERR! enoent
#36 3.210
#36 3.210 npm ERR! A complete log of this run can be found in:
#36 3.211 npm ERR!     /root/.npm/_logs/2022-01-02T10_53_10_314Z-debug.log
------
executor failed running [/bin/sh -c npm run serve]: exit code: 254
![image](https://user-images.githubusercontent.com/29866965/147881979-6f151ce2-25f8-4540-a89e-367d81171612.png)
2.服务器Vue目录下执行后bug日志
![image](https://user-images.githubusercontent.com/29866965/147882005-b1c6190a-a4fd-43b5-a523-13507e3a2076.png)
![image](https://user-images.githubusercontent.com/29866965/147882044-85a98139-d767-4903-a82d-c0c9b2a5486b.png)

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/ascotbe/Medusa/issues)，以确保该错误尚未被报告。

**Comment by Ascotbe** [comment]
不要用国内的docker镜像源，然后关于第三点，启动后台会去抓去CVE的数据，这个会需要时间，看你网路速度的，等一段时间就可以了

**Comment by Ascotbe** [comment]
关于构建还是别用国内服务器，因为国内服务器是不开25端口的，也就是说你的邮件发送功能实无法使用，测试均使用国外服务器

**Comment by Ascotbe** [comment]
![image](https://user-images.githubusercontent.com/33721903/147898716-06526304-bf35-48ec-9a88-c5ce9b9bab4e.png)
刚在测试的

**Comment by Qclover** [comment]
> 不要用国内的docker镜像源，然后关于第三点，启动后台会去抓去CVE的数据，这个会需要时间，看你网路速度的，等一段时间就可以了

感谢您的回复，但我还有两个疑问，我后来vue执行异常报错 npm run serve，也是正常吗，等拉取完cve就会好吗。
另外是否只能部署在国外服务器上自己服务器或搭建在国内或本地不行。

**Comment by Ascotbe** [comment]
> > 不要用国内的docker镜像源，然后关于第三点，启动后台会去抓去CVE的数据，这个会需要时间，看你网路速度的，等一段时间就可以了
> 
> 感谢您的回复，但我还有两个疑问，我后来vue执行异常报错 npm run serve，也是正常吗，等拉取完cve就会好吗。 另外是否只能部署在国外服务器上自己服务器或搭建在国内或本地不行。

国内服务器25端口是关闭的，就代表无法发送邮件，其他功能倒是可以正常运行，vue的问题我不太懂，前端不是我写的 ，不过我是可以正常运行的。

**Comment by Qclover** [comment]
国外服务器配置1核1G可以支持吗

**Comment by Qclover** [comment]
> > > 不要用国内的docker镜像源，然后关于第三点，启动后台会去抓去CVE的数据，这个会需要时间，看你网路速度的，等一段时间就可以了
> > 
> > 
> > 感谢您的回复，但我还有两个疑问，我后来vue执行异常报错 npm run serve，也是正常吗，等拉取完cve就会好吗。 另外是否只能部署在国外服务器上自己服务器或搭建在国内或本地不行。
> 
> 国内服务器25端口是关闭的，就代表无法发送邮件，其他功能倒是可以正常运行，vue的问题我不太懂，前端不是我写的 ，不过我是可以正常运行的。

![image](https://user-images.githubusercontent.com/29866965/148635231-5cafc2cf-fd5d-4def-8247-7fbdfe0b1c5a.png)

我在腾讯服务器上docker 构建成功了
但是web服务没有起来，http访问503
![image](https://user-images.githubusercontent.com/29866965/148635283-0f26f593-c266-4d43-883a-b7768ab60cf2.png)

**Comment by Qclover** [comment]
> > > 不要用国内的docker镜像源，然后关于第三点，启动后台会去抓去CVE的数据，这个会需要时间，看你网路速度的，等一段时间就可以了
> > 
> > 
> > 感谢您的回复，但我还有两个疑问，我后来vue执行异常报错 npm run serve，也是正常吗，等拉取完cve就会好吗。 另外是否只能部署在国外服务器上自己服务器或搭建在国内或本地不行。
> 
> 国内服务器25端口是关闭的，就代表无法发送邮件，其他功能倒是可以正常运行，vue的问题我不太懂，前端不是我写的 ，不过我是可以正常运行的。

重新执行 docker run -d -i -t --name  medusa1 -p 8082:8082 -p 9999:9999 medusa_web
之后，docker web服务起来了9999端口可以访问但8082 无法访问，
![image](https://user-images.githubusercontent.com/29866965/148635528-0a2d0839-40ab-4635-8e15-ec515cc080b8.png)
![image](https://user-images.githubusercontent.com/29866965/148635539-8e7add00-b7e8-4002-898a-69c5af2de670.png)
![image](https://user-images.githubusercontent.com/29866965/148635552-d70aa574-a650-4a7d-ae7a-ace5ed07d678.png)

**Comment by Qclover** [comment]
> > > > 不要用国内的docker镜像源，然后关于第三点，启动后台会去抓去CVE的数据，这个会需要时间，看你网路速度的，等一段时间就可以了
> > > 
> > > 
> > > 感谢您的回复，但我还有两个疑问，我后来vue执行异常报错 npm run serve，也是正常吗，等拉取完cve就会好吗。 另外是否只能部署在国外服务器上自己服务器或搭建在国内或本地不行。
> > 
> > 
> > 国内服务器25端口是关闭的，就代表无法发送邮件，其他功能倒是可以正常运行，vue的问题我不太懂，前端不是我写的 ，不过我是可以正常运行的。
> 
> 重新执行 docker run -d -i -t --name medusa1 -p 8082:8082 -p 9999:9999 medusa_web 之后，docker web服务起来了9999端口可以访问但8082 无法访问， ![image](https://user-images.githubusercontent.com/29866965/148635528-0a2d0839-40ab-4635-8e15-ec515cc080b8.png) ![image](https://user-images.githubusercontent.com/29866965/148635539-8e7add00-b7e8-4002-898a-69c5af2de670.png) ![image](https://user-images.githubusercontent.com/29866965/148635552-d70aa574-a650-4a7d-ae7a-ace5ed07d678.png)

进入容器重新运行 npm run serve成功了。但是想问一下许多功能是不是目前下线了或者是还未增加
![image](https://user-images.githubusercontent.com/29866965/148640055-be0907bc-84a4-4bb2-8084-db5336605261.png)
![image](https://user-images.githubusercontent.com/29866965/148640192-225e4813-468d-494d-87d6-c3641d61eecc.png)

这里介绍的扫描插件感觉挺多的
https://www.ddosi.org/medusa-cn/

**Comment by Ascotbe** [comment]
> > > > > 不要用国内的docker镜像源，然后关于第三点，启动后台会去抓去CVE的数据，这个会需要时间，看你网路速度的，等一段时间就可以了
> > > > 
> > > > 
> > > > 感谢您的回复，但我还有两个疑问，我后来vue执行异常报错 npm run serve，也是正常吗，等拉取完cve就会好吗。 另外是否只能部署在国外服务器上自己服务器或搭建在国内或本地不行。
> > > 
> > > 
> > > 国内服务器25端口是关闭的，就代表无法发送邮件，其他功能倒是可以正常运行，vue的问题我不太懂，前端不是我写的 ，不过我是可以正常运行的。
> > 
> > 
> > 重新执行 docker run -d -i -t --name medusa1 -p 8082:8082 -p 9999:9999 medusa_web 之后，docker web服务起来了9999端口可以访问但8082 无法访问， ![image](https://user-images.githubusercontent.com/29866965/148635528-0a2d0839-40ab-4635-8e15-ec515cc080b8.png) ![image](https://user-images.githubusercontent.com/29866965/148635539-8e7add00-b7e8-4002-898a-69c5af2de670.png) ![image](https://user-images.githubusercontent.com/29866965/148635552-d70aa574-a650-4a7d-ae7a-ace5ed07d678.png)
> 
> 进入容器重新运行 npm run serve成功了。但是想问一下许多功能是不是目前下线了或者是还未增加 ![image](https://user-images.githubusercontent.com/29866965/148640055-be0907bc-84a4-4bb2-8084-db5336605261.png) ![image](https://user-images.githubusercontent.com/29866965/148640192-225e4813-468d-494d-87d6-c3641d61eecc.png)
> 
> 这里介绍的扫描插件感觉挺多的 https://www.ddosi.org/medusa-cn/

是的有部分功能下线了，然后又写功能有后端前端还没写好，等v1.1版本上线了就好了
