### ISSUE TITLE
新功能需求

### ISSUE THREAD

**Issue by hackliu** [Ascotbe/Medusa#71]
### 这是一个什么样的功能？

建议增加
1、CVE监控
2、自定义推送功能，可将平台信息通过Server酱、BARK等平台推送到手机
3、部署文档在Ubuntu 20.04.3 LTS已不适用，建议更新。

### 这个功能可以解决什么问题？

建议增加
1、CVE监控
2、自定义推送功能，可将平台信息通过Server酱、BARK等平台推送到手机
3、部署文档在Ubuntu 20.04.3 LTS已不适用，建议更新。

### 额外描述

建议增加
1、CVE监控
2、自定义推送功能，可将平台信息通过Server酱、BARK等平台推送到手机
3、部署文档在Ubuntu 20.04.3 LTS已不适用，建议更新。

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/ascotbe/Medusa/issues)，以确保这项功能尚未被请求。

**Comment by Ascotbe** [comment]
1.功能已存在
2.自定义推送写了一半，后续会更新
3.如何不适用法，请提供说明，docker容器就是在该版本中构建的

**Comment by Qclover** [comment]
> 1.功能已存在 2.自定义推送写了一半，后续会更新 3.如何不适用法，请提供说明，docker容器就是在该版本中构建的

![image](https://user-images.githubusercontent.com/29866965/148670579-22ec5390-8047-46e9-a163-a65c4a0b709a.png)
1.026代码压缩包没这个模块github监控是不是没写完

**Comment by Ascotbe** [comment]
> > 1.功能已存在 2.自定义推送写了一半，后续会更新 3.如何不适用法，请提供说明，docker容器就是在该版本中构建的
> 
> ![image](https://user-images.githubusercontent.com/29866965/148670579-22ec5390-8047-46e9-a163-a65c4a0b709a.png) 1.026代码压缩包没这个模块github监控是不是没写完

写完了的只是没写完推送
