### ISSUE TITLE
关于安装方式的优化

### ISSUE THREAD

**Issue by dreamncn** [Ascotbe/Medusa#74]
### 这是一个什么样的功能？

Vue的部分建议直接build好了放到镜像来，docker重编译总会出现很多奇奇怪怪的问题~

PS：你们这个commit记录真的看着不迷糊吗？

### 这个功能可以解决什么问题？

简化安装

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/ascotbe/Medusa/issues)，以确保这项功能尚未被请求。

**Comment by nanshihui** [comment]
已经收到哦，我会尽快回复你。I have received your email and will reply to you ASAP. Thanks

**Comment by Ascotbe** [comment]
优化等正式发版再说吧，现在能用就行，docker编译出问题就是你网路的问题了
