### ISSUE TITLE
need a way to quickly build on localhost

### ISSUE THREAD

**Issue by csuXinda** [Ascotbe/Medusa#82]
### 这是一个什么样的功能？

Could you provide a way to build the project in own local environment without domain .Just for test and know about medusa

### 这个功能可以解决什么问题？

to run in local environment

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/ascotbe/Medusa/issues)，以确保这项功能尚未被请求。

**Comment by Ascotbe** [comment]
At present, the issue is in the schedule, and the follow-up online will @you in this issue
